# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(max_length=200)),
                ('salon_location', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=200)),
                ('salon_email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('gmaps_url', models.URLField()),
                ('avg_rating', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=200)),
                ('suitable_for', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='StyleSalon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_rating', models.CharField(max_length=20)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Salon')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Style')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StyleSalon')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('user_location', models.CharField(max_length=200)),
                ('login_via', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserStyleSalon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.CharField(max_length=20)),
                ('style_salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StyleSalon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.ManyToManyField(through='main.UserStyleSalon', to='main.StyleSalon'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AddField(
            model_name='salon',
            name='style_menu',
            field=models.ManyToManyField(through='main.StyleSalon', to='main.Style'),
        ),
    ]
