# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='avg_rating',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='salon',
            name='gmaps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='salon_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='style',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stylesalon',
            name='ss_rating',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userstylesalon',
            name='user_rating',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
