# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20151220_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salon',
            old_name='phone_num',
            new_name='salon_phone',
        ),
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=models.CharField(default=91, max_length=200),
            preserve_default=False,
        ),
    ]
