# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160203_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.Salon')),
            ],
        ),
        migrations.CreateModel(
            name='StyleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.Style')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='back_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
