# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160205_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=200)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Style')),
            ],
        ),
        migrations.AlterField(
            model_name='stylesalon',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_offers', to='main.Style'),
        ),
    ]
